ALTER TABLE ADDFRIEND
ADD CONSTRAINT ADDFRIEND_APPLICANT_EMAIL_FK
FOREIGN KEY(APPLICANT_EMAIL) REFERENCES MEMBER(EMAIL)
ON DELETE CASCADE;

ALTER TABLE ADDFRIEND
ADD CONSTRAINT ADDFRIEND_SUBJECT_EMAIL_FK
FOREIGN KEY(SUBJECT_EMAIL) REFERENCES MEMBER(EMAIL)
ON DELETE CASCADE;

ALTER TABLE QNA
ADD CONSTRAINT QNA_EMAIL_FK
FOREIGN KEY(EMAIL) REFERENCES MEMBER(EMAIL)
ON DELETE CASCADE;

ALTER TABLE AD_LIST
ADD CONSTRAINT AD_LIST_BNO_FK
FOREIGN KEY(BNO) REFERENCES BOARD(BNO)
ON DELETE CASCADE;

ALTER TABLE BOARD
ADD CONSTRAINT BOARD_EMAIL_FK
FOREIGN KEY(EMAIL) REFERENCES MEMBER(EMAIL)
ON DELETE CASCADE;

ALTER TABLE REPLY
ADD CONSTRAINT REPLY_BNO_FK
FOREIGN KEY(BNO) REFERENCES BOARD(BNO)
ON DELETE CASCADE;

ALTER TABLE BOARD_LIKE
ADD CONSTRAINT BOARD_LIKE_EMAIL_FK
FOREIGN KEY(EMAIL) REFERENCES MEMBER(EMAIL)
ON DELETE CASCADE;

ALTER TABLE SELLER
ADD CONSTRAINT SELLER_EMAIL_FK
FOREIGN KEY(EMAIL) REFERENCES MEMBER(EMAIL)
ON DELETE CASCADE;

ALTER TABLE PRODUCT
ADD CONSTRAINT PRODUCT_SNO_FK
FOREIGN KEY(SNO) REFERENCES SELLER(SNO)
ON DELETE CASCADE;

ALTER TABLE REVIEW
ADD CONSTRAINT REVIEW_PNO_FK
FOREIGN KEY(PNO) REFERENCES PRODUCT(PNO)
ON DELETE CASCADE;

ALTER TABLE CONTRACT
ADD CONSTRAINT CONTRACT_EMAIL_FK
FOREIGN KEY(EMAIL) REFERENCES MEMBER(EMAIL)
ON DELETE CASCADE;

ALTER TABLE CONTRACT
ADD CONSTRAINT CONTRACT_SNO_FK
FOREIGN KEY(SNO) REFERENCES SELLER(SNO)
ON DELETE CASCADE;

ALTER TABLE CONTRACT
ADD CONSTRAINT CONTRACT_PNO_FK
FOREIGN KEY(PNO) REFERENCES PRODUCT(PNO)
ON DELETE CASCADE;

ALTER TABLE DECLARATION
ADD CONSTRAINT DECLARATION_BNO_FK
FOREIGN KEY(BNO) REFERENCES BOARD(BNO)
ON DELETE CASCADE;

ALTER TABLE DECLARATION
ADD CONSTRAINT DECLARATION_PNO_FK
FOREIGN KEY(PNO) REFERENCES PRODUCT(PNO)
ON DELETE CASCADE;